// Generated by CoffeeScript 1.7.1
(function() {
  var StormData, StormRegistry, async, extend, ip, openvpnService, request, util;

  StormRegistry = require('stormregistry');

  StormData = require('stormdata');

  util = require('util');

  request = require('request-json');

  extend = require('util')._extend;

  ip = require('ip');

  async = require('async');

  openvpnService = (function() {
    openvpnService.prototype.start = function() {
      var client;
      if (this.openvpnServerConfig != null) {
        client = request.newClient(this.url);
        return client.post("/openvpn/server", this.openvpnServerConfig, (function(_this) {
          return function(err, res, body) {
            if (err != null) {
              util.log("post openvpn server Err  " + err);
            }
            if (body != null) {
              util.log("post openvpn result body  " + JSON.stringify(body));
            }
            if ((res != null ? res.statusCode : void 0) != null) {
              return util.log("post openvpn status code res statuscode" + res.statusCode);
            }
          };
        })(this));
      }
    };

    openvpnService.prototype.stop = function() {};

    openvpnService.prototype.update = function() {};

    function openvpnService(url, config) {
      this.url = url;
      console.log("openvpn url is " + this.url);
      if ((config != null ? config.server : void 0) != null) {
        this.openvpnServerConfig = extend({}, config.server);
      }
      if ((config != null ? config.client : void 0) != null) {
        this.openvpnClientConfig = extend({}, config.server);
      }
      util.log("openvpnServerConfig   " + this.openvpnServerConfig);
      util.log("openvpnClientConfig " + this.openvpnClientConfig);
    }

    return openvpnService;

  })();

  module.exports = openvpnService;

}).call(this);
