// Generated by CoffeeScript 1.7.1
this.app = require('zappajs')(5671, function() {
  var pv;
  this.configure((function(_this) {
    return function() {
      _this.use('bodyParser', 'methodOverride', _this.app.router, 'static');
      return _this.set({
        'basepath': '/v1.0'
      });
    };
  })(this));
  this.configure({
    development: (function(_this) {
      return function() {
        return _this.use({
          errorHandler: {
            dumpExceptions: true,
            showStack: true
          }
        });
      };
    })(this),
    production: (function(_this) {
      return function() {
        return _this.use('errorHandler');
      };
    })(this)
  });
  this.enable('serve jquery', 'minify');
  pv = require('./provisioner');
  this.post({
    '/provision': function() {
      console.log("post provision vm received" + JSON.stringify(this.body));
      return pv.create(this.body, (function(_this) {
        return function(res) {
          console.log("post switch response" + res);
          return _this.send(res);
        };
      })(this));
    }
  });
  return this.get({
    '/provison/:id': function() {
      console.log(" get provison id received");
      return pv.list((function(_this) {
        return function(res) {
          console.log("get switch response " + res);
          return _this.send(res);
        };
      })(this));
    }
  });
}).app;
